import MainLayout from "../layouts/MainLayout"

function Reports() {
  return (
    <MainLayout>

      <h2 className="text-2xl font-bold mb-6">
        Audit Reports & Analytics
      </h2>

      {/* Statistics Cards */}
      <div className="grid grid-cols-4 gap-6 mb-8">

        <div className="bg-white shadow rounded-lg p-6">
          <h3 className="text-gray-500 text-sm">Total Audits</h3>
          <p className="text-3xl font-bold">248</p>
          <span className="text-green-600 text-sm">+12%</span>
        </div>

        <div className="bg-white shadow rounded-lg p-6">
          <h3 className="text-gray-500 text-sm">Audit Yield</h3>
          <p className="text-3xl font-bold">Br 2.4M</p>
          <span className="text-green-600 text-sm">+8%</span>
        </div>

        <div className="bg-white shadow rounded-lg p-6">
          <h3 className="text-gray-500 text-sm">Completion Rate</h3>
          <p className="text-3xl font-bold">78%</p>
          <span className="text-yellow-600 text-sm">On Track</span>
        </div>

        <div className="bg-white shadow rounded-lg p-6">
          <h3 className="text-gray-500 text-sm">Active Auditors</h3>
          <p className="text-3xl font-bold">42</p>
          <span className="text-blue-600 text-sm">Full Capacity</span>
        </div>

      </div>

      {/* Chart Placeholder */}
      <div className="bg-white shadow rounded-lg p-6 mb-8">
        <h3 className="text-lg font-semibold mb-4">
          Monthly Audit Completion
        </h3>
        <div className="h-64 bg-gray-100 flex items-center justify-center">
          <p className="text-gray-500">Chart will be displayed here</p>
        </div>
      </div>

      {/* Report Filters */}
      <div className="bg-white shadow rounded-lg p-6 mb-8">
        <h3 className="text-lg font-semibold mb-4">
          Generate Reports
        </h3>

        <div className="grid grid-cols-3 gap-4">

          <select className="border p-2 rounded">
            <option>Report Type</option>
            <option>Audit Status</option>
            <option>Productivity Report</option>
            <option>Assessment Summary</option>
            <option>Fraud Cases</option>
          </select>

          <select className="border p-2 rounded">
            <option>Period</option>
            <option>This Month</option>
            <option>This Quarter</option>
            <option>This Year</option>
            <option>Custom Range</option>
          </select>

          <button className="bg-blue-600 text-white px-4 py-2 rounded">
            Generate Report
          </button>

        </div>
      </div>

      {/* Recent Reports Table */}
      <div className="bg-white shadow rounded-lg p-6">
        <h3 className="text-lg font-semibold mb-4">
          Recently Generated Reports
        </h3>

        <table className="min-w-full">
          <thead className="bg-gray-100">
            <tr>
              <th className="text-left px-4 py-2">Report Name</th>
              <th className="text-left px-4 py-2">Generated By</th>
              <th className="text-left px-4 py-2">Date</th>
              <th className="text-left px-4 py-2">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-t">
              <td className="px-4 py-2">Monthly Audit Summary</td>
              <td className="px-4 py-2">John Auditor</td>
              <td className="px-4 py-2">2024-01-15</td>
              <td className="px-4 py-2">
                <span className="bg-green-100 text-green-800 px-2 py-1 rounded text-sm">Completed</span>
              </td>
            </tr>
            <tr className="border-t">
              <td className="px-4 py-2">Auditor Productivity</td>
              <td className="px-4 py-2">Sara Manager</td>
              <td className="px-4 py-2">2024-01-14</td>
              <td className="px-4 py-2">
                <span className="bg-yellow-100 text-yellow-800 px-2 py-1 rounded text-sm">Pending</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

    </MainLayout>
  )
}

export default Reports